name: "Update controls_signalduino.txt files"
description: "Runs fhem-controls-actions for FHEM, FHEM/lib, and lib/FHEM/Devices/SIGNALduino"
runs:
  using: "composite"
  steps:
    - name: update controls file (FHEM)
      uses: fhem/fhem-controls-actions@v3.0.0
      with:
        filename: controls_signalduino.txt 
    - name: update controls file (lib)
      uses: fhem/fhem-controls-actions@v3.0.0
      with:
        filename: controls_signalduino.txt 
        directory: FHEM/lib
        writemode: a
    - name: update controls file (perl lib)
      uses: fhem/fhem-controls-actions@v3.0.0
      with:
        filename: controls_signalduino.txt 
        directory: lib/FHEM/Devices/SIGNALduino
        writemode: a
    - name: update controls file (perl lib)
      uses: fhem/fhem-controls-actions@v3.0.0
      with:
        filename: controls_signalduino.txt 
        directory: lib/FHEM/Devices/SIGNALduino/SD_Protocols
        writemode: a
