runner:
  perl-test2-tap:
    cmd: cat testOutput
    errorformat: # (optional if you use `format`)
     - '%C# at %f line %l%.'
     - '%E# Failed test %m'
     - '%C# | %.%#'
     - '%C# +-%.%#'
     - '%-G%.%#'
  perl-errors:
    cmd: perl -ne 'print if ! $a{substr $_,22}++' testOutput 
    errorformat:
      - "%-G%m redefined at %f line %l%.%r"
      - "%+E%.%# at %f line %l%.%r"
      - "%+ZBEGIN failed%r"
      - "%-Gok%.%#"
