runner:
  perl-test2-tap:
    cmd: cat errorformat
    errorformat: # (optional if you use `format`)
      - "%E# Failed test %m"
      - "%C# at %f line %l%."
      - "%C# %m"
      - "%-G%.%#"
  perl-errors:
    cmd: cat errorformat
    errorformat:
      #- "%+E%.%#Error:%r"
      - "%+E%.%# at %f line %l%.%r"
      - "%+ZBEGIN failed%r"
     

