sudo: enabled
language: perl
jobs:
  include:
  - perl: "5.26@cover"
  - perl: "5.24@cover"
  - perl: "5.18@cover"
    before_script:
      - cpanm List::Util --notest 
cache:
   directories:
      - $HOME/perl5
env:
  global:
    secure: QZkNIahKdBIE/ANg04akx6MNgFItbLVSvGrR2By6rjHqrU9kllv862aVmcOjJw5/lcewEgRMgdK8ddhCKunW5HKpgW9CrkTi2GYVcmnJpw39ye7UnIIyOJM1N3YC+vWAaru+LJh8rHkXSfopKiiOjq9uTtfFCt+kngP7oIRKfPJ/7qdgKWvYpqKnqGoFoXghBWKe3V63xunILMkRVeTg+ogBOXbRy+3OU4WBIc4DsGdKOz+XkTecjLM9sdoyYLWUodLcmqwfCNGKWKwjVOaIe+859QtIoAEkclJtXunn6wYOeaumAJ+dILKZmOt4ORQxVYtVs+3W0eUl8+Z12xi6SGCenIQQGFHjxQgbjekXCiN56vf5LQUlxSEktjK67o9tq3+8VpgnPxqAgFOh4CvX4Ite3IT2+mPMegFOJavuyN/xOTuZgTe3sXDJzCfDBTQdBrb94ex/eZWZPn0M5Dkupiegh1CK6lJFVUwHpcJWb11SI2hzQRsGtPmlxDOfi48n23gVt7/bDeJS8rUlQoehF5fTVY1lMo4SZkB1Zs/ykm+NjPFg7h03j9E1msGFE/wQOZsN550GSxnpacZT9HandaxundiQHmVUfHHR54ieLxd3/xSTjqEpZcai21Oiq2ghmagGp8s+eRdNejMWLVWuHuWynFr72XU3LSXBW6YWyIc=
git:
  depth: false
before_install:
 - eval $(curl https://travis-perl.github.io/init) --perl --always-upgrade-modules
 - perl -V
 - git config --global user.email "travis@travis-ci.org"
 - git config --global user.name "Travis CI"
 - git config --global push.default simple
 - git remote set-url origin https://${GH_API_KEY}@github.com/RFD-FHEM/RFFHEM.git
 - wget -qO - http://debian.fhem.de/archive.key | sudo apt-key add - || true
 - echo "deb http://debian.fhem.de/nightly/ /" | sudo tee -a /etc/apt/sources.list || true
install:
 - cpanm Device::SerialPort File::Find File::Basename Mock::Sub Test::More Test::Device::SerialPort Devel::Cover Devel::Cover::Report::Coveralls  JSON Net::SSLeay --notest 
 - sudo apt-get update -qq
 - sudo apt-get install fhem -y || (curl -sLO http://fhem.de/fhem-5.9.deb && sudo apt install ./fhem-5.9.deb)
 - sudo chown travis -R /opt/fhem
 - sudo /etc/init.d/fhem stop
 # - sudo service fhem stop
script:
 - timeout 40 bash -c 'while /usr/bin/pgrep perl >> /dev/null; do sleep 1; echo .; done;'
 - make test 
 - sudo pkill "^perl" || true
 - timeout 40 bash -c 'while /usr/bin/pgrep perl >> /dev/null; do sleep 1; echo .; done;' || sudo pkill "^perl"
 - sleep 3
 - ./build_controls_list.sh 
 - git commit -m "Travis automatic update controls file. Build (${TRAVIS_BUILD_NUMBER}) [skip ci]" ./controls_signalduino.txt || true
 - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [[ $TRAVIS_JOB_NUMBER == *.1 ]]; then git push origin HEAD:$TRAVIS_BRANCH ; fi'
 - cp -R /opt/fhem/cover_db ./
 - if [ "$FULL_COVER" != "true" ]; then git --no-pager diff --diff-filter=d --name-only $TRAVIS_COMMIT_RANGE | grep .pm | xargs -I@ echo -select @ | xargs cover -report coveralls; fi
 - if [ "$FULL_COVER" = "true" ]; then git ls-tree --full-tree -r --name-only HEAD ./FHEM | grep .pm | xargs -I@ echo -select @ | xargs cover -report coveralls; fi

after_failure:
 - UnitTest/src/report_failure.sh
