name: Perlcritic
on: [workflow_dispatch,pull_request]

jobs:
  critic:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Perl Critic
      uses: Difegue/action-perlcritic@2.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
          args: ./FHEM/* 